apiVersion: v1
kind: PersistentVolume
metadata:
  name: rick-fs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/asia-northeast1-b/rick-rl-test/rick_rl_tpu"
    volumeAttributes:
      ip: 10.0.0.17
      volume: rick_rl_tpu
      protocol: nfsv3
  claimRef:
    name: rick-fs-pvc
    namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rick-fs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
