apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: tpu-v6e-4x4-flavor
spec:
  nodeLabels:
    cloud.google.com/gke-tpu-accelerator: ct6e
    cloud.google.com/gke-tpu-topology: 4x4
  tolerations:
  - effect: NoSchedule
    key: google.com/tpu
    value: "present"
  - effect: NoSchedule
    key: cloud.google.com/gke-queued
    operator: Equal
    value: "true"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ProvisioningRequestConfig
metadata:
  name: dws-v6e-4x4-config
spec:
  provisioningClassName: queued-provisioning.gke.io
  managedResources:
  - google.com/tpu
  parameters:
    tpu-topology: "4x4"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: AdmissionCheck
metadata:
  name: dws-v6e-4x4-prov
spec:
  controllerName: kueue.x-k8s.io/provisioning-request
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: ProvisioningRequestConfig
    name: dws-v6e-4x4-config
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: cluster-queue-v6e-4x4
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["google.com/tpu"]
    flavors:
    - name: tpu-v6e-4x4-flavor
      resources:
      - name: google.com/tpu
        nominalQuota: 16
  admissionChecks:
  - dws-v6e-4x4-prov
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  namespace: default
  name: dws-v6e-4x4-local-queue
spec:
  clusterQueue: cluster-queue-v6e-4x4
